apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: "{{$.iios.services.auth.replicas}}"
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: "ignitial/auth:{{$.iios.services.auth.version}}"
        imagePullPolicy: "{{$.iios.services.auth.imagePullPolicy}}"
        ports: "{{$.iios.services.auth.ports}}"
        env:
          - name: IIOS_NAMESPACE
            value: "{{$.iios.namespace}}"
          - name: IIOS_SERVER_HOST
            value: "auth.default.svc.cluster.local"
          - name: IIOS_SERVER_PORT
            value: "{{str($.iios.services.auth.ports[0].containerPort)}}"
          - name: IIOS_REDIS_HOST
            value: "redis.default.svc.cluster.local"
          - name: IIOS_REDIS_PORT
            value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: "{{$.iios.services.auth.ports[0].containerPort}}"
    targetPort: "{{$.iios.services.auth.ports[0].containerPort}}"
