version: "3.3"
services:
  reflib:
    image: registry.gitlab.com/ignitial/reflib:${IIOS_APP_VERSION}
    depends_on:
      - redis
      - dlake
      - auth
    networks:
      - proxy
      - infra
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webnotsecured.rule=Host(`mydomain.com`)"
        - "traefik.http.routers.webnotsecured.entrypoints=web"
        - "traefik.http.routers.webnotsecured.middlewares=httpsredirect"
        - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
        - "traefik.http.routers.reflib.rule=Host(`mydomain.com`)"
        - "traefik.http.routers.reflib.entrypoints=websecure"
        - "traefik.http.routers.reflib.tls.certresolver=myhttpchallenge"
        - "traefik.http.services.app_service.loadbalancer.server.port=80"
    environment:
      - NODE_ENV=production
      - IIOS_SERVER_PORT=80
      - IIOS_IIOS_NAMESPACE=reflib
      - IIOS_REDIS_HOST=redis
      - IIOS_S3_BUCKET=iio1393
      - IIOS_S3_REGION=fr-par
      - IIOS_S3_SECURE=true
      - IIOS_S3_ENDPOINT=s3.fr-par.scw.cloud
      - IIOS_EMAILER_SMTP_USER=support@ignitial.fr
      - IIOS_EMAILER_SMTP_HOST=mail.gandi.net
      - IIOS_EMAILER_SMTP_PORT=587
    secrets:
      - emailer_smtp_pass
      - s3_access_key_id
      - s3_secret_access_key

  dlake:
    image: ignitial/dlake:${IIOS_DLAKE_VERSION}
    depends_on:
      - redis
    networks:
      - infra
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_MONGODB_URI=iiomc1-hvphm.gcp.mongodb.net
      - IIOS_MONGODB_USER=ignitial
      - IIOS_MONGODB_OPTIONS=retryWrites=true
      - IIOS_MONGODB_CONN_MAX_ATTEMPTS=60
      - IIOS_POPULATE=true
      - IIOS_DBNAME=reflib
      - IIOS_NAMESPACE=reflib
      - IIOS_SERVER_HOST=dlake
      - IIOS_SERVER_PORT=20991
    networks:
      infra:
    secrets:
      - mongodb_pwd

  auth:
    image: ignitial/auth:${IIOS_AUTH_VERSION}
    depends_on:
      - redis
    networks:
      - infra
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=reflib
      - IIOS_SERVER_HOST=auth
      - IIOS_SERVER_PORT=20199

  redis:
    image: redis:5.0.5-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.role==manager]
    volumes:
      - redis-data:/data
    networks:
      infra:

volumes:
  redis-data:

networks:
  infra:
    external: true
  proxy:
    external: true

secrets:
  s3_access_key_id:
    external: true
  s3_secret_access_key:
    external: true
  emailer_smtp_pass:
    external: true
  mongodb_pwd:
    external: true
