apiVersion: 1
defs:
  connector:
    redis:
      encoder: bson
      # sentinels: sentinel
      host: redis.default.svc.cluster.local
      port: 6379
      db: 0
server:
  port: 80
  path: ./dist
  filesDropPath: ./dropped
  corsEnabled: false
rest:
  logLevel: error
logout:
  # minutes
  timeout: 15
  _unified: true
store:
  minio:
    endPoint: s3.fr-par.scw.cloud
    useSSL: true
    bucket: iio1393
    region: fr-par
    port:
    accessKey: "{{env(IIOS_S3_ACCESS_KEY_ID)}}"
    secretKey: "{{env(IIOS_S3_SECRET_ACCESS_KEY)}}"
  bucket:
    name: iio1393
    region: fr-par
    endPoint: s3.fr-par.scw.cloud
    _unified: true
modules:
  gateway:
    namespace: reflib
    # calling timeout for pub/sub mode
    timeout: 5000
    connector: "{{$.defs.connector}}"
  emailer:
    smtp:
      host: mail.ignitial.fr
      port: 25
      secure: false
      auth:
        user: ignitial
        pass: "{{env(IIOS_EMAILER_SMTP_PASS)}}"
      logger: false
      debug: false
    mail:
      from: Systra Support <no-reply@ignitial.fr>
# data service information
data:
  # name of the main service that provides data access
  service: dlake
  # additional collections
  collections:
    - name: schemas
      options:
        indexes:
          - key: name
            type: -1
            options:
              name: name_desc
              unique: true
    - name: notifications
    - name: connections
    # deployables
    - name: deployables
      options:
        indexes:
          - key: name
            type: -1
            options:
              name: name_desc
              unique: true
        grants:
          __privileged__:
            'dlake:deployables':
              'create:any':
                - '*'
              'read:any':
                - '*'
              'update:any':
                - '*'
              'delete:any':
                - '*'
          admin:
            'dlake:deployables':
              'create:any':
                - '*'
              'read:any':
                - '*'
              'update:any':
                - '*'
              'delete:any':
                - '*'
          user:
            'dlake:deployables':
              'create:any':
                - '*'
              'read:any':
                - '*'
              'update:any':
                - '*'
              'delete:any':
                - '*'
          anonymous:
            'dlake:deployables':
              'read:any':
                - '*'
  _unified: true
# auth service information
auth:
  # name of the main service that provides authentication control
  service: auth
  _unified: true
i18n: "{{yamlfile(./i18n.yaml)}}"
unified:
  settings:
    rpcTimeout: 10000
    _unified: true
  options:
    apigateway:
      namespace: reflib
      # calling timeout for pub/sub mode
      timeout: 5000
      connector: "{{$.defs.connector}}"
    myunified:
      someConfiguration: that's all folks !
