apiVersion: 1
languages:
  - "fr-FR"
  - "es-ES"
data:
  "Search":
    - "Recherche"
    - "Buscar"
  "Settings":
    - "Paramètres"
    - "Opciones"
  "Geolocation":
    - "Géolocalisation"
    - "Geolocalización"
  "Geolocation not available":
    - "Geolocalisation indisponible"
    - "Geolocalización indisponible"
  "Dashboard":
    - "Tableau de bord"
    - "Panel de control"
  "Users":
    - "Utilisateurs"
    - "Usuarios"
  "Map":
    - "Carte"
    - "Mapa"
  "Ok":
    - "Fermer"
    - "Cerrar"
  "Create":
    - "Créer"
    - "Crear"
  "Delete":
    - "Effacer"
    - "Borrar"
  "Username":
    - "Nom d'utilisateur"
    - "Nombre de usuario"
  "Sign in":
    - "Se connecter"
    - "Conectarse"
  "Sign out":
    - "Se déconnecter"
    - "Desconectarse"
  "Sign into your account":
    - "Connectez-vous à votre compte"
    - "Conéctese a su cuenta"
  "Sign up":
    - "S'inscrire"
    - "Registrarse"
  "Bad username or password":
    - "Utilisateur ou mot de passe incorrect"
    - "Usuario o contraseña incorrectos"
  "Create your user account":
    - "Créer votre compte utilisateur"
    - "Crear una cuenta de usuario"
  "Update":
    - "Mettre à jour"
    - "Actualizar"
  "Import":
    - "Importer"
    - "Importar"
  "Avatar":
    - "Image de profil"
    - "Foto de perfil"
  "Password":
    - "Mot de passe"
    - "Contraseña"
  "Get notifications by email":
    - "Recevoir les notifications par courriel"
    - "Recibir las notificaciones por correo"
  "User settings":
    - "Paramètres d'utilisation"
    - "Opciones de usuario"
  "Profile settings":
    - "Préférences de profil"
    - "Opciones de perfil"
  "User profile":
    - "Profil utilisateur"
    - "Perfil de usuario"
  "Last connection date":
    - "Dernière date de connexion"
    - "Ultima fecha de conexión"
  "Validate":
    - "Valider"
    - "Validar"
  "Apply":
    - "Valider"
    - "Aplicar"
  "Cancel":
    - "Abandonner"
    - "Cancelar"
  "Image must be less than 50kb":
    - "L'image doit être inférieure à 50ko"
    - "La imagen debe ser inferior a 50kb"
  "Log into your account or sign up if new":
    - "Connectez-vous à votre compte ou inscrivez-vous"
    - "Conectarse a su cuenta o registrarse"
  "Value":
    - "Valeur"
    - "Valor"
  "3D view":
    - "Vue 3D"
    - "Vista 3D"
  "Geographical location":
    - "Localisation géographique"
    - "Ubicación geográfica"
  "Geographical shape":
    - "Forme géographique"
    - "Forma geográfica"
  "Modification done":
    - "Modification réalisée"
    - "Cambio realizado"
  "Modification failed":
    - "Modification échouée"
    - "Cambio fallido"
  "Do you want to update":
    - "Voulez-vous mettre à jour"
    - "¿Desea actualizar?"
  "January":
    - "Janvier"
    - "Enero"
  "February":
    - "Février"
    - "Febrero"
  "March":
    - "Mars"
    - "Marzo"
  "April":
    - "Avril"
    - "Abril"
  "May":
    - "Mai"
    - "Mayo"
  "June":
    - "Juin"
    - "Junio"
  "July":
    - "Juillet"
    - "Julio"
  "August":
    - "Août"
    - "Agosto"
  "September":
    - "Septembre"
    - "Septiembre"
  "October":
    - "Octobre"
    - "Octubre"
  "November":
    - "Novembre"
    - "Noviembre"
  "December":
    - "Décembre"
    - "Diciembre"
  "Alarms":
    - "Alarmes"
    - "Alarmas"
  "Password has been succesfully modified":
    - "Le mot de passe a été modifié avec succès"
    - "Contraseña modificada con éxito"
  "Failed to modifiy password":
    - "Le mot de passe n'a pu être modifié"
    - "No se pudo cambiar la contraseña"
  "Failed to upload file":
    - "Impossible de charger le fichier"
    - "No se pudo cargar el arhivo"
  "Element type":
    - "Type de l'élément"
    - "Tipo de elemento"
  "Possible values":
    - "Valeurs possibles"
    - "Valores posibles"
  "comma separated":
    - "séparé(e)(s) par ,"
    - "Separado por coma"
  "Enumerate":
    - "Enuméré"
    - "Enumerado"
  "Items specifically constrained":
    - "Items spécifiquement contraints"
    - "Elementos específicamente restringidos"
  "Element":
    - "Elément"
    - "Elemento"
  "Item type":
    - "Type de l'item"
    - "Tipo de item"
  "Property identifier":
    - "Identifiant de la propriété"
    - "Identificador de propiedades"
  "Helper type":
    - "Type d'assistant"
    - "Tipo de asistente"
  "File":
    - "Fichier"
    - "Archivo"
  "Do you confirm item deletion ?":
    - "Confirmez-vous l'effacement de cet item ?"
    - "¿Desea borrar el item ?"
  "File type":
    - "Type de fichier"
    - "Tipo de archivo"
  "Helper settings":
    - "Paramètres de l'assistant"
    - "Opciones del asistente"
  "Any type":
    - "Type quelconque"
    - "Cualquier tipo"
  "File max size":
    - "Taille maximale du fichier"
    - "Tamaño máximo del archivo"
  "Show thumbnail":
    - "Afficher une vignette"
    - "Mostrar miniatura"
  "Icon":
    - "Icône"
    - "Icono"
  "Group":
    - "Groupe"
    - "Grupo"
  "Edit":
    - "Éditer"
    - "Editar"
  "Add child":
    - "Ajouter un enfant"
    - "Agregar un hijo"
  "Expand all":
    - "Déployer toutes les branches"
    - "Expandir todo"
  "Filter":
    - "Filtre"
    - "Filtro"
  "None":
    - "Aucun"
    - "Ninguno"
  "Reset":
    - "Réinitialiser"
    - "Reiniciar"
  "Drop files here to upload":
    - "Déposer les fichiers ici pour les charger"
    - "Depositar los archivos aquí para subirlos"
  "`File must be less than ${ params[0] } kb`":
    - "`Le fichier doit être inférieur à ${ params[0] } ko`"
    - "`El archivo debe ser inferior a ${ params[0] } kb`"
  "File too big":
    - "Fichier trop grand"
    - "Archivo demasiado grande"
  "Your updates have been validated":
    - "Vos informations ont été validées"
    - "Sus actualizaciones han sido validadas"
  "Your updates have been rejected":
    - "Vos informations ont été rejetées"
    - "Sus informaciones han sido rechazadas"
  "Administration":
    - "Administration"
    - "Administración"
  "Services":
    - "Services"
    - "Servicios"
  "Modules":
    - "Modules"
    - "Módulos"
  "RPC timeout":
    - "Délai RPC"
    - "Retraso RPC"
  "Role":
    - "Rôle"
    - "Rol"
  "App is offline. Check your network connection":
    - "L'application est hors ligne. Vérifiez la connexion réseau"
    - "La application está desconectada. Verifica la red"
  "Element has been added remotely":
    - "Un élément a été ajouté par un client tiers"
    - "Un elemento estó añadido por un altro cliente"
  "Element has been updated remotely":
    - "Un élément a été mis à jour par un client tiers"
    - "Un elemento estó actualizado por un altro cliente"
  "Element has been removed remotely":
    - "Un élément a été supprimé par un client tiers"
    - "Un elemento estó actualizado por un altro cliente"
  "Property detailed type":
    - "Type détaillé de la propriété"
    - "Tipo detallado de propiedad"
  "Schema edit":
    - "Edition de schéma"
    - "Edición del schema"
  "File upload":
    - "Chargement de fichier"
    - "Carga de archivo"
  "Drop file(s) here or click to browse":
    - "Déposer le(s) fichier(s) ici ou cliquer pour parcourir"
    - "Envíe el (los) archivo (s) aquí o haga clic para navegar"
  "Date format":
    - "Format date"
    - "Formato de fetcha"
  "Time format":
    - "Format heure"
    - "Formato de hore"
  "Date and time format":
    - "Format date et heure"
    - "Formato de fetcha y hora"
  "Test":
    - "Test"
    - "Prueba"
  "Add item":
    - "Ajouter un item"
    - "Añadir un itemo"
  "Load schema":
    - "Charger un schéma"
    - "Cargar un schema"
  "Load item":
    - "Charger un item"
    - "Cargar un item"
  "`File ${ params[0] } uploaded`":
    - "`Fichier ${ params[0] } chargé`"
    - "`Archivo ${ params[0] } cargado`"
  "Save item":
    - "Sauvegarder l'item"
    - "Guardar el artículo"
  "You must define a schema first":
    - "Vous devez définir un schéma"
    - "Debe definir un esquema"
  "No related schema":
    - "Pas de schéma correspondant"
    - "Sin esquema de correspondencia"
_unified: true
