---
# Source: redis-ha/templates/redis-ha-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reflib-redis-ha
  labels:
    heritage: Tiller
    release: reflib
    chart: redis-ha-3.7.1
    app: reflib-redis-ha
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
