---
# Source: redis-ha/templates/redis-ha-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflib-redis-ha
  labels:
    heritage: Tiller
    release: reflib
    chart: redis-ha-3.7.1
    app: reflib-redis-ha
