version: '3.3'

services:
  auth:
    image: ignitial/auth:${IIOS_AUTH_VERSION}
    container_name: auth
    ports:
      - "20199:20199"
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20199
    networks:
      infra:

  dlake:
    image: registry.ignitial.io/ignitial/dlake:${IIOS_APP_VERSION}
    volumes:
      - ${PWD}/datum:/opt/dlake/datum
    ports:
      - "20991:20991"
    environment:
      - IIOS_REDIS_MASTER_NAME=mymaster
      - IIOS_REDIS_SENTINELS=sentinel
      - IIOS_MONGODB_URI=mongodb://mongo:27017
      - IIOS_DBNAME=reflib
      - IIOS_POPULATE=true
      - IIOS_NAMESPACE=reflib
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20991
    networks:
      iio:
      infra:

  reflib:
    image: registry.ignitial.io/ignitial/reflib:${IIOS_APP_VERSION}
    volumes:
      - ${PWD}:/opt/reflib
    environment:
      - IIOS_SERVER_PORT=8080
      - IIOS_NAMESPACE=reflib
      - IIOS_MONGODB_URI=mongodb://mongo:27017
      - IIOS_REDIS_MASTER_NAME=mymaster
      - IIOS_REDIS_SENTINELS=sentinel
      - IIOS_S3_ENDPOINT=s3.amazonaws.com
      - IIOS_S3_BUCKET=636ojbq68oou95ut5ayq8yd9c9n6cm5c
      - IIOS_S3_SECURE=true
      - IIOS_S3_REGION=eu-west-3
      - IIOS_EMAILER_SMTP_USER=support@ignitial.fr
      - IIOS_EMAILER_SMTP_HOST=mail.gandi.net
      - IIOS_EMAILER_SMTP_PORT=587
    secrets:
      - s3_access_key_id
      - s3_secret_access_key
      - emailer_smtp_pass
    ports:
      - "8080:8080"
    networks:
      iio:
      infra:

networks:
  iio:
  infra:
    external: true

secrets:
  s3_access_key_id:
    external: true
  s3_secret_access_key:
    external: true
  emailer_smtp_pass:
    external: true
  mongodb_pwd:
    external: true
